-- ============================================================================
-- File: 003_seed_color_lexicon.sql
-- Purpose: Seed exactly 500 curated, representative terminology mappings.
-- Dependencies: 001_create_color_lexicon_schema.sql,
--               002_seed_canonical_colors.sql
-- Rerun behavior: Deterministic upsert by normalized_term.
-- Source note: source identifies a terminology category, not verified provenance
--              from a particular publication, retailer, designer, or brand.
-- ============================================================================

BEGIN;

WITH seed(term, normalized_term, canonical_name, confidence_weight, source) AS (
    VALUES
    ('Black', 'black', 'Black', 1.00, 'manual'),
    ('jet black', 'jet black', 'Black', 0.95, 'fashion'),
    ('kohl black', 'kohl black', 'Black', 0.90, 'cosmetic'),
    ('pure black', 'pure black', 'Black', 0.90, 'retail'),
    ('lacquer black', 'lacquer black', 'Black', 0.86, 'designer'),
    ('washed black', 'washed black', 'Black', 0.82, 'streetwear'),
    ('all-black', 'all black', 'Black', 0.78, 'social_media'),
    ('pitch black', 'pitch black', 'Black', 0.88, 'regional'),
    ('onyx black', 'onyx black', 'Black', 0.76, 'marketing'),
    ('midnight black', 'midnight black', 'Black', 0.86, 'luxury'),
    ('antique black', 'antique black', 'Black', 0.80, 'vintage'),
    ('black gabardine', 'black gabardine', 'Black', 0.92, 'textile'),
    ('inky black', 'inky black', 'Black', 0.88, 'editorial'),
    ('Charcoal', 'charcoal', 'Charcoal', 1.00, 'manual'),
    ('charcoal gray', 'charcoal gray', 'Charcoal', 0.95, 'fashion'),
    ('carbon black', 'carbon black', 'Charcoal', 0.90, 'cosmetic'),
    ('charcoal pigment', 'charcoal pigment', 'Charcoal', 0.90, 'retail'),
    ('dark charcoal', 'dark charcoal', 'Charcoal', 0.86, 'designer'),
    ('washed charcoal', 'washed charcoal', 'Charcoal', 0.82, 'streetwear'),
    ('smoke black', 'smoke black', 'Charcoal', 0.78, 'social_media'),
    ('charcoal grey', 'charcoal grey', 'Charcoal', 0.88, 'regional'),
    ('graphite charcoal', 'graphite charcoal', 'Charcoal', 0.76, 'marketing'),
    ('anthracite', 'anthracite', 'Charcoal', 0.86, 'luxury'),
    ('vintage charcoal', 'vintage charcoal', 'Charcoal', 0.80, 'vintage'),
    ('charcoal wool', 'charcoal wool', 'Charcoal', 0.92, 'textile'),
    ('editorial charcoal', 'editorial charcoal', 'Charcoal', 0.88, 'editorial'),
    ('Gray', 'gray', 'Gray', 1.00, 'manual'),
    ('neutral gray', 'neutral gray', 'Gray', 0.95, 'fashion'),
    ('ash gray', 'ash gray', 'Gray', 0.90, 'cosmetic'),
    ('dove gray', 'dove gray', 'Gray', 0.90, 'retail'),
    ('mid gray', 'mid gray', 'Gray', 0.86, 'designer'),
    ('concrete gray', 'concrete gray', 'Gray', 0.82, 'streetwear'),
    ('smoke', 'smoke', 'Gray', 0.55, 'social_media'),
    ('grey', 'grey', 'Gray', 0.88, 'regional'),
    ('stone', 'stone', 'Gray', 0.58, 'marketing'),
    ('pewter gray', 'pewter gray', 'Gray', 0.86, 'luxury'),
    ('battleship gray', 'battleship gray', 'Gray', 0.80, 'vintage'),
    ('gray flannel', 'gray flannel', 'Gray', 0.92, 'textile'),
    ('editorial gray', 'editorial gray', 'Gray', 0.88, 'editorial'),
    ('Silver', 'silver', 'Silver', 1.00, 'manual'),
    ('metallic silver', 'metallic silver', 'Silver', 0.95, 'fashion'),
    ('silver shimmer', 'silver shimmer', 'Silver', 0.90, 'cosmetic'),
    ('silver foil', 'silver foil', 'Silver', 0.90, 'retail'),
    ('liquid silver', 'liquid silver', 'Silver', 0.86, 'designer'),
    ('chrome silver', 'chrome silver', 'Silver', 0.82, 'streetwear'),
    ('cyber silver', 'cyber silver', 'Silver', 0.78, 'social_media'),
    ('silver grey', 'silver grey', 'Silver', 0.88, 'regional'),
    ('moonlight silver', 'moonlight silver', 'Silver', 0.76, 'marketing'),
    ('sterling silver', 'sterling silver', 'Silver', 0.86, 'luxury'),
    ('antique silver', 'antique silver', 'Silver', 0.80, 'vintage'),
    ('silver lamé', 'silver lame', 'Silver', 0.92, 'textile'),
    ('space-age silver', 'space age silver', 'Silver', 0.88, 'editorial'),
    ('White', 'white', 'White', 1.00, 'manual'),
    ('optic white', 'optic white', 'White', 0.95, 'fashion'),
    ('porcelain white', 'porcelain white', 'White', 0.90, 'cosmetic'),
    ('pure white', 'pure white', 'White', 0.90, 'retail'),
    ('runway white', 'runway white', 'White', 0.86, 'designer'),
    ('sneaker white', 'sneaker white', 'White', 0.82, 'streetwear'),
    ('clean-girl white', 'clean girl white', 'White', 0.78, 'social_media'),
    ('brilliant white', 'brilliant white', 'White', 0.88, 'regional'),
    ('paper white', 'paper white', 'White', 0.76, 'marketing'),
    ('gallery white', 'gallery white', 'White', 0.86, 'luxury'),
    ('antique white', 'antique white', 'White', 0.80, 'vintage'),
    ('white poplin', 'white poplin', 'White', 0.92, 'textile'),
    ('editorial white', 'editorial white', 'White', 0.88, 'editorial'),
    ('Ivory', 'ivory', 'Ivory', 1.00, 'manual'),
    ('ivory silk', 'ivory silk', 'Ivory', 0.95, 'fashion'),
    ('ivory foundation', 'ivory foundation', 'Ivory', 0.90, 'cosmetic'),
    ('soft ivory', 'soft ivory', 'Ivory', 0.90, 'retail'),
    ('bridal ivory', 'bridal ivory', 'Ivory', 0.86, 'designer'),
    ('off-white ivory', 'off white ivory', 'Ivory', 0.82, 'streetwear'),
    ('eggshell', 'eggshell', 'Ivory', 0.78, 'social_media'),
    ('ivory white', 'ivory white', 'Ivory', 0.88, 'regional'),
    ('ecru', 'ecru', 'Ivory', 0.76, 'marketing'),
    ('luxe ivory', 'luxe ivory', 'Ivory', 0.86, 'luxury'),
    ('vintage ivory', 'vintage ivory', 'Ivory', 0.80, 'vintage'),
    ('ivory linen', 'ivory linen', 'Ivory', 0.92, 'textile'),
    ('editorial ivory', 'editorial ivory', 'Ivory', 0.88, 'editorial'),
    ('Cream', 'cream', 'Cream', 1.00, 'manual'),
    ('creamy white', 'creamy white', 'Cream', 0.95, 'fashion'),
    ('cream concealer', 'cream concealer', 'Cream', 0.90, 'cosmetic'),
    ('soft cream', 'soft cream', 'Cream', 0.90, 'retail'),
    ('runway cream', 'runway cream', 'Cream', 0.86, 'designer'),
    ('vanilla cream', 'vanilla cream', 'Cream', 0.82, 'streetwear'),
    ('cream fit', 'cream fit', 'Cream', 0.78, 'social_media'),
    ('crème', 'creme', 'Cream', 0.88, 'regional'),
    ('buttermilk cream', 'buttermilk cream', 'Cream', 0.76, 'marketing'),
    ('cashmere cream', 'cashmere cream', 'Cream', 0.86, 'luxury'),
    ('antique cream', 'antique cream', 'Cream', 0.80, 'vintage'),
    ('cream satin', 'cream satin', 'Cream', 0.92, 'textile'),
    ('editorial cream', 'editorial cream', 'Cream', 0.88, 'editorial'),
    ('Beige', 'beige', 'Beige', 1.00, 'manual'),
    ('fashion beige', 'fashion beige', 'Beige', 0.95, 'fashion'),
    ('nude', 'nude', 'Beige', 0.55, 'cosmetic'),
    ('natural beige', 'natural beige', 'Beige', 0.90, 'retail'),
    ('designer beige', 'designer beige', 'Beige', 0.86, 'designer'),
    ('oatmeal', 'oatmeal', 'Beige', 0.82, 'streetwear'),
    ('beige aesthetic', 'beige aesthetic', 'Beige', 0.78, 'social_media'),
    ('biscuit beige', 'biscuit beige', 'Beige', 0.88, 'regional'),
    ('sand', 'sand', 'Beige', 0.58, 'marketing'),
    ('greige', 'greige', 'Beige', 0.86, 'luxury'),
    ('vintage beige', 'vintage beige', 'Beige', 0.80, 'vintage'),
    ('beige twill', 'beige twill', 'Beige', 0.92, 'textile'),
    ('quiet-luxury beige', 'quiet luxury beige', 'Beige', 0.88, 'editorial'),
    ('Tan', 'tan', 'Tan', 1.00, 'manual'),
    ('suntan brown', 'suntan brown', 'Tan', 0.95, 'fashion'),
    ('bronzer tan', 'bronzer tan', 'Tan', 0.90, 'cosmetic'),
    ('classic tan', 'classic tan', 'Tan', 0.90, 'retail'),
    ('runway tan', 'runway tan', 'Tan', 0.86, 'designer'),
    ('workwear tan', 'workwear tan', 'Tan', 0.82, 'streetwear'),
    ('tan fit', 'tan fit', 'Tan', 0.78, 'social_media'),
    ('camel', 'camel', 'Tan', 0.58, 'regional'),
    ('desert tan', 'desert tan', 'Tan', 0.76, 'marketing'),
    ('saddle tan', 'saddle tan', 'Tan', 0.86, 'luxury'),
    ('tobacco tan', 'tobacco tan', 'Tan', 0.80, 'vintage'),
    ('tan suede', 'tan suede', 'Tan', 0.92, 'textile'),
    ('editorial tan', 'editorial tan', 'Tan', 0.88, 'editorial'),
    ('Brown', 'brown', 'Brown', 1.00, 'manual'),
    ('true brown', 'true brown', 'Brown', 0.95, 'fashion'),
    ('earth brown', 'earth brown', 'Brown', 0.90, 'cosmetic'),
    ('brown eye shadow', 'brown eye shadow', 'Brown', 0.90, 'retail'),
    ('classic brown', 'classic brown', 'Brown', 0.86, 'designer'),
    ('designer brown', 'designer brown', 'Brown', 0.82, 'streetwear'),
    ('brown streetwear', 'brown streetwear', 'Brown', 0.78, 'social_media'),
    ('brown colour', 'brown colour', 'Brown', 0.88, 'regional'),
    ('wood brown', 'wood brown', 'Brown', 0.76, 'marketing'),
    ('luxe brown', 'luxe brown', 'Brown', 0.86, 'luxury'),
    ('vintage brown', 'vintage brown', 'Brown', 0.80, 'vintage'),
    ('brown corduroy', 'brown corduroy', 'Brown', 0.92, 'textile'),
    ('editorial brown', 'editorial brown', 'Brown', 0.88, 'editorial'),
    ('Chocolate', 'chocolate', 'Chocolate', 1.00, 'manual'),
    ('dark chocolate', 'dark chocolate', 'Chocolate', 0.95, 'fashion'),
    ('cocoa', 'cocoa', 'Chocolate', 0.90, 'cosmetic'),
    ('chocolate brown', 'chocolate brown', 'Chocolate', 0.90, 'retail'),
    ('ganache', 'ganache', 'Chocolate', 0.86, 'designer'),
    ('mocha chocolate', 'mocha chocolate', 'Chocolate', 0.82, 'streetwear'),
    ('espresso brown', 'espresso brown', 'Chocolate', 0.78, 'social_media'),
    ('chocolate colour', 'chocolate colour', 'Chocolate', 0.88, 'regional'),
    ('cacao', 'cacao', 'Chocolate', 0.76, 'marketing'),
    ('truffle brown', 'truffle brown', 'Chocolate', 0.86, 'luxury'),
    ('vintage cocoa', 'vintage cocoa', 'Chocolate', 0.80, 'vintage'),
    ('chocolate velvet', 'chocolate velvet', 'Chocolate', 0.92, 'textile'),
    ('editorial chocolate', 'editorial chocolate', 'Chocolate', 0.88, 'editorial'),
    ('Red', 'red', 'Red', 1.00, 'manual'),
    ('true red', 'true red', 'Red', 0.95, 'fashion'),
    ('lipstick red', 'lipstick red', 'Red', 0.90, 'cosmetic'),
    ('primary red', 'primary red', 'Red', 0.90, 'retail'),
    ('runway red', 'runway red', 'Red', 0.86, 'designer'),
    ('cherry red', 'cherry red', 'Red', 0.82, 'streetwear'),
    ('tomato red', 'tomato red', 'Red', 0.78, 'social_media'),
    ('colour red', 'colour red', 'Red', 0.88, 'regional'),
    ('fire-engine red', 'fire engine red', 'Red', 0.76, 'marketing'),
    ('ruby', 'ruby', 'Red', 0.86, 'luxury'),
    ('vintage red', 'vintage red', 'Red', 0.80, 'vintage'),
    ('red satin', 'red satin', 'Red', 0.92, 'textile'),
    ('statement red', 'statement red', 'Red', 0.88, 'editorial'),
    ('Scarlet', 'scarlet', 'Scarlet', 1.00, 'manual'),
    ('scarlet dress', 'scarlet dress', 'Scarlet', 0.95, 'fashion'),
    ('scarlet lipstick', 'scarlet lipstick', 'Scarlet', 0.90, 'cosmetic'),
    ('bright scarlet', 'bright scarlet', 'Scarlet', 0.90, 'retail'),
    ('runway scarlet', 'runway scarlet', 'Scarlet', 0.86, 'designer'),
    ('scarlet sneakers', 'scarlet sneakers', 'Scarlet', 0.82, 'streetwear'),
    ('scarletcore', 'scarletcore', 'Scarlet', 0.78, 'social_media'),
    ('British scarlet', 'british scarlet', 'Scarlet', 0.88, 'regional'),
    ('vermilion scarlet', 'vermilion scarlet', 'Scarlet', 0.76, 'marketing'),
    ('imperial scarlet', 'imperial scarlet', 'Scarlet', 0.86, 'luxury'),
    ('vintage scarlet', 'vintage scarlet', 'Scarlet', 0.80, 'vintage'),
    ('scarlet silk', 'scarlet silk', 'Scarlet', 0.92, 'textile'),
    ('editorial scarlet', 'editorial scarlet', 'Scarlet', 0.88, 'editorial'),
    ('Crimson', 'crimson', 'Crimson', 1.00, 'manual'),
    ('crimson fashion', 'crimson fashion', 'Crimson', 0.95, 'fashion'),
    ('crimson lip', 'crimson lip', 'Crimson', 0.90, 'cosmetic'),
    ('deep crimson', 'deep crimson', 'Crimson', 0.90, 'retail'),
    ('couture crimson', 'couture crimson', 'Crimson', 0.86, 'designer'),
    ('crimson streetwear', 'crimson streetwear', 'Crimson', 0.82, 'streetwear'),
    ('crimson aesthetic', 'crimson aesthetic', 'Crimson', 0.78, 'social_media'),
    ('crimson colour', 'crimson colour', 'Crimson', 0.88, 'regional'),
    ('rich crimson', 'rich crimson', 'Crimson', 0.76, 'marketing'),
    ('royal crimson', 'royal crimson', 'Crimson', 0.86, 'luxury'),
    ('antique crimson', 'antique crimson', 'Crimson', 0.80, 'vintage'),
    ('crimson velvet', 'crimson velvet', 'Crimson', 0.92, 'textile'),
    ('editorial crimson', 'editorial crimson', 'Crimson', 0.88, 'editorial'),
    ('Burgundy', 'burgundy', 'Burgundy', 1.00, 'manual'),
    ('oxblood', 'oxblood', 'Burgundy', 0.95, 'fashion'),
    ('wine', 'wine', 'Burgundy', 0.58, 'cosmetic'),
    ('wine red', 'wine red', 'Burgundy', 0.90, 'retail'),
    ('Bordeaux red', 'bordeaux red', 'Burgundy', 0.86, 'designer'),
    ('burgundy streetwear', 'burgundy streetwear', 'Burgundy', 0.82, 'streetwear'),
    ('merlot red', 'merlot red', 'Burgundy', 0.78, 'social_media'),
    ('claret', 'claret', 'Burgundy', 0.88, 'regional'),
    ('dark cherry wine', 'dark cherry wine', 'Burgundy', 0.76, 'marketing'),
    ('garnet burgundy', 'garnet burgundy', 'Burgundy', 0.86, 'luxury'),
    ('vintage burgundy', 'vintage burgundy', 'Burgundy', 0.80, 'vintage'),
    ('burgundy leather', 'burgundy leather', 'Burgundy', 0.92, 'textile'),
    ('editorial burgundy', 'editorial burgundy', 'Burgundy', 0.88, 'editorial'),
    ('Coral Red', 'coral red', 'Coral Red', 1.00, 'manual'),
    ('coral', 'coral', 'Coral Red', 0.95, 'fashion'),
    ('coral lipstick', 'coral lipstick', 'Coral Red', 0.90, 'cosmetic'),
    ('bright coral', 'bright coral', 'Coral Red', 0.90, 'retail'),
    ('runway coral', 'runway coral', 'Coral Red', 0.86, 'designer'),
    ('coral sneakers', 'coral sneakers', 'Coral Red', 0.82, 'streetwear'),
    ('coral aesthetic', 'coral aesthetic', 'Coral Red', 0.78, 'social_media'),
    ('coral colour', 'coral colour', 'Coral Red', 0.88, 'regional'),
    ('sunset coral', 'sunset coral', 'Coral Red', 0.76, 'marketing'),
    ('precious coral', 'precious coral', 'Coral Red', 0.86, 'luxury'),
    ('retro coral', 'retro coral', 'Coral Red', 0.80, 'vintage'),
    ('coral chiffon', 'coral chiffon', 'Coral Red', 0.92, 'textile'),
    ('editorial coral', 'editorial coral', 'Coral Red', 0.88, 'editorial'),
    ('Orange', 'orange', 'Orange', 1.00, 'manual'),
    ('fashion orange', 'fashion orange', 'Orange', 0.95, 'fashion'),
    ('orange blush', 'orange blush', 'Orange', 0.90, 'cosmetic'),
    ('bright orange', 'bright orange', 'Orange', 0.90, 'retail'),
    ('runway orange', 'runway orange', 'Orange', 0.86, 'designer'),
    ('safety orange', 'safety orange', 'Orange', 0.82, 'streetwear'),
    ('orange-core', 'orange core', 'Orange', 0.78, 'social_media'),
    ('orange colour', 'orange colour', 'Orange', 0.88, 'regional'),
    ('rust', 'rust', 'Orange', 0.58, 'marketing'),
    ('burnished orange', 'burnished orange', 'Orange', 0.86, 'luxury'),
    ('vintage orange', 'vintage orange', 'Orange', 0.80, 'vintage'),
    ('orange canvas', 'orange canvas', 'Orange', 0.92, 'textile'),
    ('editorial orange', 'editorial orange', 'Orange', 0.88, 'editorial'),
    ('Peach', 'peach', 'Peach', 1.00, 'manual'),
    ('peach fashion', 'peach fashion', 'Peach', 0.95, 'fashion'),
    ('peach blush', 'peach blush', 'Peach', 0.90, 'cosmetic'),
    ('soft peach', 'soft peach', 'Peach', 0.90, 'retail'),
    ('runway peach', 'runway peach', 'Peach', 0.86, 'designer'),
    ('peach streetwear', 'peach streetwear', 'Peach', 0.82, 'streetwear'),
    ('peach aesthetic', 'peach aesthetic', 'Peach', 0.78, 'social_media'),
    ('peach colour', 'peach colour', 'Peach', 0.88, 'regional'),
    ('apricot peach', 'apricot peach', 'Peach', 0.76, 'marketing'),
    ('silk peach', 'silk peach', 'Peach', 0.86, 'luxury'),
    ('vintage peach', 'vintage peach', 'Peach', 0.80, 'vintage'),
    ('peach organza', 'peach organza', 'Peach', 0.92, 'textile'),
    ('editorial peach', 'editorial peach', 'Peach', 0.88, 'editorial'),
    ('Yellow', 'yellow', 'Yellow', 1.00, 'manual'),
    ('sunshine yellow', 'sunshine yellow', 'Yellow', 0.95, 'fashion'),
    ('lemon', 'lemon', 'Yellow', 0.90, 'cosmetic'),
    ('primary yellow', 'primary yellow', 'Yellow', 0.90, 'retail'),
    ('runway yellow', 'runway yellow', 'Yellow', 0.86, 'designer'),
    ('yellow sneakers', 'yellow sneakers', 'Yellow', 0.82, 'streetwear'),
    ('yellow aesthetic', 'yellow aesthetic', 'Yellow', 0.78, 'social_media'),
    ('yellow colour', 'yellow colour', 'Yellow', 0.88, 'regional'),
    ('canary', 'canary', 'Yellow', 0.76, 'marketing'),
    ('radiant yellow', 'radiant yellow', 'Yellow', 0.86, 'luxury'),
    ('vintage yellow', 'vintage yellow', 'Yellow', 0.80, 'vintage'),
    ('yellow cotton', 'yellow cotton', 'Yellow', 0.92, 'textile'),
    ('editorial yellow', 'editorial yellow', 'Yellow', 0.88, 'editorial'),
    ('Butter Yellow', 'butter yellow', 'Butter Yellow', 1.00, 'manual'),
    ('buttery yellow', 'buttery yellow', 'Butter Yellow', 0.95, 'fashion'),
    ('buttercream yellow', 'buttercream yellow', 'Butter Yellow', 0.90, 'cosmetic'),
    ('soft butter', 'soft butter', 'Butter Yellow', 0.90, 'retail'),
    ('runway butter yellow', 'runway butter yellow', 'Butter Yellow', 0.86, 'designer'),
    ('butter-yellow fit', 'butter yellow fit', 'Butter Yellow', 0.82, 'streetwear'),
    ('butter yellow aesthetic', 'butter yellow aesthetic', 'Butter Yellow', 0.78, 'social_media'),
    ('pale butter yellow', 'pale butter yellow', 'Butter Yellow', 0.88, 'regional'),
    ('melted butter', 'melted butter', 'Butter Yellow', 0.76, 'marketing'),
    ('cashmere yellow', 'cashmere yellow', 'Butter Yellow', 0.86, 'luxury'),
    ('vintage butter yellow', 'vintage butter yellow', 'Butter Yellow', 0.80, 'vintage'),
    ('butter yellow silk', 'butter yellow silk', 'Butter Yellow', 0.92, 'textile'),
    ('editorial butter yellow', 'editorial butter yellow', 'Butter Yellow', 0.88, 'editorial'),
    ('Gold', 'gold', 'Gold', 1.00, 'manual'),
    ('metallic gold', 'metallic gold', 'Gold', 0.95, 'fashion'),
    ('gold shimmer', 'gold shimmer', 'Gold', 0.90, 'cosmetic'),
    ('gold foil', 'gold foil', 'Gold', 0.90, 'retail'),
    ('liquid gold', 'liquid gold', 'Gold', 0.86, 'designer'),
    ('gold sneakers', 'gold sneakers', 'Gold', 0.82, 'streetwear'),
    ('gold aesthetic', 'gold aesthetic', 'Gold', 0.78, 'social_media'),
    ('golden colour', 'golden colour', 'Gold', 0.88, 'regional'),
    ('gold leaf', 'gold leaf', 'Gold', 0.76, 'marketing'),
    ('luxe gold', 'luxe gold', 'Gold', 0.86, 'luxury'),
    ('antique gold', 'antique gold', 'Gold', 0.80, 'vintage'),
    ('gold lamé', 'gold lame', 'Gold', 0.92, 'textile'),
    ('Green', 'green', 'Green', 1.00, 'manual'),
    ('fashion green', 'fashion green', 'Green', 0.95, 'fashion'),
    ('green eye shadow', 'green eye shadow', 'Green', 0.90, 'cosmetic'),
    ('true green', 'true green', 'Green', 0.90, 'retail'),
    ('forest green', 'forest green', 'Green', 0.86, 'designer'),
    ('chartreuse', 'chartreuse', 'Green', 0.82, 'streetwear'),
    ('brat green', 'brat green', 'Green', 0.78, 'social_media'),
    ('green colour', 'green colour', 'Green', 0.88, 'regional'),
    ('fresh green', 'fresh green', 'Green', 0.76, 'marketing'),
    ('jewel green', 'jewel green', 'Green', 0.86, 'luxury'),
    ('vintage green', 'vintage green', 'Green', 0.80, 'vintage'),
    ('green taffeta', 'green taffeta', 'Green', 0.92, 'textile'),
    ('Olive', 'olive', 'Olive', 1.00, 'manual'),
    ('olive green', 'olive green', 'Olive', 0.95, 'fashion'),
    ('olive makeup', 'olive makeup', 'Olive', 0.90, 'cosmetic'),
    ('army olive', 'army olive', 'Olive', 0.90, 'retail'),
    ('runway olive', 'runway olive', 'Olive', 0.86, 'designer'),
    ('pistachio', 'pistachio', 'Olive', 0.82, 'streetwear'),
    ('olive aesthetic', 'olive aesthetic', 'Olive', 0.78, 'social_media'),
    ('khaki olive', 'khaki olive', 'Olive', 0.88, 'regional'),
    ('martini olive', 'martini olive', 'Olive', 0.76, 'marketing'),
    ('luxe olive', 'luxe olive', 'Olive', 0.86, 'luxury'),
    ('vintage olive', 'vintage olive', 'Olive', 0.80, 'vintage'),
    ('olive twill', 'olive twill', 'Olive', 0.92, 'textile'),
    ('Sage', 'sage', 'Sage', 1.00, 'manual'),
    ('sage green', 'sage green', 'Sage', 0.95, 'fashion'),
    ('sage eye shadow', 'sage eye shadow', 'Sage', 0.90, 'cosmetic'),
    ('soft sage', 'soft sage', 'Sage', 0.90, 'retail'),
    ('runway sage', 'runway sage', 'Sage', 0.86, 'designer'),
    ('sage streetwear', 'sage streetwear', 'Sage', 0.82, 'streetwear'),
    ('sage aesthetic', 'sage aesthetic', 'Sage', 0.78, 'social_media'),
    ('grey sage', 'grey sage', 'Sage', 0.88, 'regional'),
    ('herbal sage', 'herbal sage', 'Sage', 0.76, 'marketing'),
    ('silken sage', 'silken sage', 'Sage', 0.86, 'luxury'),
    ('vintage sage', 'vintage sage', 'Sage', 0.80, 'vintage'),
    ('sage linen', 'sage linen', 'Sage', 0.92, 'textile'),
    ('Mint', 'mint', 'Mint', 1.00, 'manual'),
    ('mint green', 'mint green', 'Mint', 0.95, 'fashion'),
    ('mint makeup', 'mint makeup', 'Mint', 0.90, 'cosmetic'),
    ('soft mint', 'soft mint', 'Mint', 0.90, 'retail'),
    ('runway mint', 'runway mint', 'Mint', 0.86, 'designer'),
    ('mint sneakers', 'mint sneakers', 'Mint', 0.82, 'streetwear'),
    ('mint aesthetic', 'mint aesthetic', 'Mint', 0.78, 'social_media'),
    ('mint colour', 'mint colour', 'Mint', 0.88, 'regional'),
    ('peppermint green', 'peppermint green', 'Mint', 0.76, 'marketing'),
    ('luxe mint', 'luxe mint', 'Mint', 0.86, 'luxury'),
    ('vintage mint', 'vintage mint', 'Mint', 0.80, 'vintage'),
    ('mint chiffon', 'mint chiffon', 'Mint', 0.92, 'textile'),
    ('Emerald', 'emerald', 'Emerald', 1.00, 'manual'),
    ('emerald green', 'emerald green', 'Emerald', 0.95, 'fashion'),
    ('emerald eye shadow', 'emerald eye shadow', 'Emerald', 0.90, 'cosmetic'),
    ('deep emerald', 'deep emerald', 'Emerald', 0.90, 'retail'),
    ('runway emerald', 'runway emerald', 'Emerald', 0.86, 'designer'),
    ('emerald streetwear', 'emerald streetwear', 'Emerald', 0.82, 'streetwear'),
    ('emerald aesthetic', 'emerald aesthetic', 'Emerald', 0.78, 'social_media'),
    ('emerald colour', 'emerald colour', 'Emerald', 0.88, 'regional'),
    ('jewel emerald', 'jewel emerald', 'Emerald', 0.76, 'marketing'),
    ('precious emerald', 'precious emerald', 'Emerald', 0.86, 'luxury'),
    ('vintage emerald', 'vintage emerald', 'Emerald', 0.80, 'vintage'),
    ('emerald velvet', 'emerald velvet', 'Emerald', 0.92, 'textile'),
    ('Lime', 'lime', 'Lime', 1.00, 'manual'),
    ('lime green', 'lime green', 'Lime', 0.95, 'fashion'),
    ('lime pigment', 'lime pigment', 'Lime', 0.90, 'cosmetic'),
    ('electric lime', 'electric lime', 'Lime', 0.90, 'retail'),
    ('runway lime', 'runway lime', 'Lime', 0.86, 'designer'),
    ('acid lime', 'acid lime', 'Lime', 0.82, 'streetwear'),
    ('neon-lime aesthetic', 'neon lime aesthetic', 'Lime', 0.78, 'social_media'),
    ('lime colour', 'lime colour', 'Lime', 0.88, 'regional'),
    ('citrus lime', 'citrus lime', 'Lime', 0.76, 'marketing'),
    ('luxe lime', 'luxe lime', 'Lime', 0.86, 'luxury'),
    ('retro lime', 'retro lime', 'Lime', 0.80, 'vintage'),
    ('lime mesh', 'lime mesh', 'Lime', 0.92, 'textile'),
    ('Blue', 'blue', 'Blue', 1.00, 'manual'),
    ('fashion blue', 'fashion blue', 'Blue', 0.95, 'fashion'),
    ('blue eye shadow', 'blue eye shadow', 'Blue', 0.90, 'cosmetic'),
    ('primary blue', 'primary blue', 'Blue', 0.90, 'retail'),
    ('cerulean', 'cerulean', 'Blue', 0.86, 'designer'),
    ('blue streetwear', 'blue streetwear', 'Blue', 0.82, 'streetwear'),
    ('electric blue', 'electric blue', 'Blue', 0.78, 'social_media'),
    ('blue colour', 'blue colour', 'Blue', 0.88, 'regional'),
    ('clear blue', 'clear blue', 'Blue', 0.76, 'marketing'),
    ('jewel blue', 'jewel blue', 'Blue', 0.86, 'luxury'),
    ('vintage blue', 'vintage blue', 'Blue', 0.80, 'vintage'),
    ('blue satin', 'blue satin', 'Blue', 0.92, 'textile'),
    ('Navy', 'navy', 'Navy', 1.00, 'manual'),
    ('navy blue', 'navy blue', 'Navy', 0.95, 'fashion'),
    ('navy eyeliner', 'navy eyeliner', 'Navy', 0.90, 'cosmetic'),
    ('dark navy', 'dark navy', 'Navy', 0.90, 'retail'),
    ('runway navy', 'runway navy', 'Navy', 0.86, 'designer'),
    ('navy streetwear', 'navy streetwear', 'Navy', 0.82, 'streetwear'),
    ('midnight navy', 'midnight navy', 'Navy', 0.78, 'social_media'),
    ('navy colour', 'navy colour', 'Navy', 0.88, 'regional'),
    ('ink navy', 'ink navy', 'Navy', 0.76, 'marketing'),
    ('luxe navy', 'luxe navy', 'Navy', 0.86, 'luxury'),
    ('vintage navy', 'vintage navy', 'Navy', 0.80, 'vintage'),
    ('navy wool', 'navy wool', 'Navy', 0.92, 'textile'),
    ('Cobalt Blue', 'cobalt blue', 'Cobalt Blue', 1.00, 'manual'),
    ('cobalt', 'cobalt', 'Cobalt Blue', 0.95, 'fashion'),
    ('cobalt eye shadow', 'cobalt eye shadow', 'Cobalt Blue', 0.90, 'cosmetic'),
    ('bright cobalt', 'bright cobalt', 'Cobalt Blue', 0.90, 'retail'),
    ('runway cobalt', 'runway cobalt', 'Cobalt Blue', 0.86, 'designer'),
    ('cobalt sneakers', 'cobalt sneakers', 'Cobalt Blue', 0.82, 'streetwear'),
    ('cobalt aesthetic', 'cobalt aesthetic', 'Cobalt Blue', 0.78, 'social_media'),
    ('cobalt colour', 'cobalt colour', 'Cobalt Blue', 0.88, 'regional'),
    ('electric cobalt', 'electric cobalt', 'Cobalt Blue', 0.76, 'marketing'),
    ('porcelain cobalt', 'porcelain cobalt', 'Cobalt Blue', 0.86, 'luxury'),
    ('vintage cobalt', 'vintage cobalt', 'Cobalt Blue', 0.80, 'vintage'),
    ('cobalt silk', 'cobalt silk', 'Cobalt Blue', 0.92, 'textile'),
    ('Azure', 'azure', 'Azure', 1.00, 'manual'),
    ('azure blue', 'azure blue', 'Azure', 0.95, 'fashion'),
    ('azure pigment', 'azure pigment', 'Azure', 0.90, 'cosmetic'),
    ('bright azure', 'bright azure', 'Azure', 0.90, 'retail'),
    ('runway azure', 'runway azure', 'Azure', 0.86, 'designer'),
    ('azure streetwear', 'azure streetwear', 'Azure', 0.82, 'streetwear'),
    ('azure aesthetic', 'azure aesthetic', 'Azure', 0.78, 'social_media'),
    ('azure colour', 'azure colour', 'Azure', 0.88, 'regional'),
    ('clear-sky azure', 'clear sky azure', 'Azure', 0.76, 'marketing'),
    ('luxe azure', 'luxe azure', 'Azure', 0.86, 'luxury'),
    ('vintage azure', 'vintage azure', 'Azure', 0.80, 'vintage'),
    ('azure chiffon', 'azure chiffon', 'Azure', 0.92, 'textile'),
    ('Sky Blue', 'sky blue', 'Sky Blue', 1.00, 'manual'),
    ('clear sky blue', 'clear sky blue', 'Sky Blue', 0.95, 'fashion'),
    ('sky-blue makeup', 'sky blue makeup', 'Sky Blue', 0.90, 'cosmetic'),
    ('soft sky blue', 'soft sky blue', 'Sky Blue', 0.90, 'retail'),
    ('runway sky blue', 'runway sky blue', 'Sky Blue', 0.86, 'designer'),
    ('sky-blue sneakers', 'sky blue sneakers', 'Sky Blue', 0.82, 'streetwear'),
    ('sky blue aesthetic', 'sky blue aesthetic', 'Sky Blue', 0.78, 'social_media'),
    ('sky blue colour', 'sky blue colour', 'Sky Blue', 0.88, 'regional'),
    ('daylight blue', 'daylight blue', 'Sky Blue', 0.76, 'marketing'),
    ('silken sky', 'silken sky', 'Sky Blue', 0.86, 'luxury'),
    ('vintage sky blue', 'vintage sky blue', 'Sky Blue', 0.80, 'vintage'),
    ('sky blue poplin', 'sky blue poplin', 'Sky Blue', 0.92, 'textile'),
    ('Denim Blue', 'denim blue', 'Denim Blue', 1.00, 'manual'),
    ('denim', 'denim', 'Denim Blue', 0.95, 'fashion'),
    ('blue-jean makeup', 'blue jean makeup', 'Denim Blue', 0.90, 'cosmetic'),
    ('classic denim blue', 'classic denim blue', 'Denim Blue', 0.90, 'retail'),
    ('designer denim', 'designer denim', 'Denim Blue', 0.86, 'designer'),
    ('streetwear denim', 'streetwear denim', 'Denim Blue', 0.82, 'streetwear'),
    ('double-denim blue', 'double denim blue', 'Denim Blue', 0.78, 'social_media'),
    ('blue jean', 'blue jean', 'Denim Blue', 0.88, 'regional'),
    ('indigo denim', 'indigo denim', 'Denim Blue', 0.76, 'marketing'),
    ('selvedge blue', 'selvedge blue', 'Denim Blue', 0.86, 'luxury'),
    ('vintage denim', 'vintage denim', 'Denim Blue', 0.80, 'vintage'),
    ('denim twill', 'denim twill', 'Denim Blue', 0.92, 'textile'),
    ('Purple', 'purple', 'Purple', 1.00, 'manual'),
    ('fashion purple', 'fashion purple', 'Purple', 0.95, 'fashion'),
    ('purple eye shadow', 'purple eye shadow', 'Purple', 0.90, 'cosmetic'),
    ('true purple', 'true purple', 'Purple', 0.90, 'retail'),
    ('runway purple', 'runway purple', 'Purple', 0.86, 'designer'),
    ('purple streetwear', 'purple streetwear', 'Purple', 0.82, 'streetwear'),
    ('purple aesthetic', 'purple aesthetic', 'Purple', 0.78, 'social_media'),
    ('purple colour', 'purple colour', 'Purple', 0.88, 'regional'),
    ('royal purple', 'royal purple', 'Purple', 0.76, 'marketing'),
    ('luxe purple', 'luxe purple', 'Purple', 0.86, 'luxury'),
    ('vintage purple', 'vintage purple', 'Purple', 0.80, 'vintage'),
    ('purple satin', 'purple satin', 'Purple', 0.92, 'textile'),
    ('Violet', 'violet', 'Violet', 1.00, 'manual'),
    ('violet purple', 'violet purple', 'Violet', 0.95, 'fashion'),
    ('violet eye shadow', 'violet eye shadow', 'Violet', 0.90, 'cosmetic'),
    ('deep violet', 'deep violet', 'Violet', 0.90, 'retail'),
    ('runway violet', 'runway violet', 'Violet', 0.86, 'designer'),
    ('violet sneakers', 'violet sneakers', 'Violet', 0.82, 'streetwear'),
    ('violet aesthetic', 'violet aesthetic', 'Violet', 0.78, 'social_media'),
    ('violet colour', 'violet colour', 'Violet', 0.88, 'regional'),
    ('electric violet', 'electric violet', 'Violet', 0.76, 'marketing'),
    ('jewel violet', 'jewel violet', 'Violet', 0.86, 'luxury'),
    ('vintage violet', 'vintage violet', 'Violet', 0.80, 'vintage'),
    ('violet velvet', 'violet velvet', 'Violet', 0.92, 'textile'),
    ('Lavender', 'lavender', 'Lavender', 1.00, 'manual'),
    ('lavender purple', 'lavender purple', 'Lavender', 0.95, 'fashion'),
    ('lavender makeup', 'lavender makeup', 'Lavender', 0.90, 'cosmetic'),
    ('soft lavender', 'soft lavender', 'Lavender', 0.90, 'retail'),
    ('runway lavender', 'runway lavender', 'Lavender', 0.86, 'designer'),
    ('lavender streetwear', 'lavender streetwear', 'Lavender', 0.82, 'streetwear'),
    ('lavender aesthetic', 'lavender aesthetic', 'Lavender', 0.78, 'social_media'),
    ('lavender colour', 'lavender colour', 'Lavender', 0.88, 'regional'),
    ('pastel lavender', 'pastel lavender', 'Lavender', 0.76, 'marketing'),
    ('silken lavender', 'silken lavender', 'Lavender', 0.86, 'luxury'),
    ('vintage lavender', 'vintage lavender', 'Lavender', 0.80, 'vintage'),
    ('lavender organza', 'lavender organza', 'Lavender', 0.92, 'textile'),
    ('Pink', 'pink', 'Pink', 1.00, 'manual'),
    ('fashion pink', 'fashion pink', 'Pink', 0.95, 'fashion'),
    ('blush', 'blush', 'Pink', 0.90, 'cosmetic'),
    ('true pink', 'true pink', 'Pink', 0.90, 'retail'),
    ('ballet pink', 'ballet pink', 'Pink', 0.86, 'designer'),
    ('pink streetwear', 'pink streetwear', 'Pink', 0.82, 'streetwear'),
    ('hot-pink aesthetic', 'hot pink aesthetic', 'Pink', 0.78, 'social_media'),
    ('pink colour', 'pink colour', 'Pink', 0.88, 'regional'),
    ('candy pink', 'candy pink', 'Pink', 0.76, 'marketing'),
    ('luxe pink', 'luxe pink', 'Pink', 0.86, 'luxury'),
    ('vintage pink', 'vintage pink', 'Pink', 0.80, 'vintage'),
    ('pink satin', 'pink satin', 'Pink', 0.92, 'textile'),
    ('Powder Pink', 'powder pink', 'Powder Pink', 1.00, 'manual'),
    ('powdery pink', 'powdery pink', 'Powder Pink', 0.95, 'fashion'),
    ('powder-pink blush', 'powder pink blush', 'Powder Pink', 0.90, 'cosmetic'),
    ('soft powder pink', 'soft powder pink', 'Powder Pink', 0.90, 'retail'),
    ('runway powder pink', 'runway powder pink', 'Powder Pink', 0.86, 'designer'),
    ('powder-pink sneakers', 'powder pink sneakers', 'Powder Pink', 0.82, 'streetwear'),
    ('powder pink aesthetic', 'powder pink aesthetic', 'Powder Pink', 0.78, 'social_media'),
    ('powder pink colour', 'powder pink colour', 'Powder Pink', 0.88, 'regional'),
    ('baby powder pink', 'baby powder pink', 'Powder Pink', 0.76, 'marketing'),
    ('silken powder pink', 'silken powder pink', 'Powder Pink', 0.86, 'luxury'),
    ('vintage powder pink', 'vintage powder pink', 'Powder Pink', 0.80, 'vintage'),
    ('powder pink chiffon', 'powder pink chiffon', 'Powder Pink', 0.92, 'textile'),
    ('Fuchsia', 'fuchsia', 'Fuchsia', 1.00, 'manual'),
    ('fuchsia pink', 'fuchsia pink', 'Fuchsia', 0.95, 'fashion'),
    ('fuchsia lipstick', 'fuchsia lipstick', 'Fuchsia', 0.90, 'cosmetic'),
    ('bright fuchsia', 'bright fuchsia', 'Fuchsia', 0.90, 'retail'),
    ('runway fuchsia', 'runway fuchsia', 'Fuchsia', 0.86, 'designer'),
    ('fuchsia streetwear', 'fuchsia streetwear', 'Fuchsia', 0.82, 'streetwear'),
    ('fuchsia aesthetic', 'fuchsia aesthetic', 'Fuchsia', 0.78, 'social_media'),
    ('fuchsia colour', 'fuchsia colour', 'Fuchsia', 0.88, 'regional'),
    ('electric fuchsia', 'electric fuchsia', 'Fuchsia', 0.76, 'marketing'),
    ('jewel fuchsia', 'jewel fuchsia', 'Fuchsia', 0.86, 'luxury'),
    ('vintage fuchsia', 'vintage fuchsia', 'Fuchsia', 0.80, 'vintage'),
    ('fuchsia satin', 'fuchsia satin', 'Fuchsia', 0.92, 'textile'),
    ('Rose Pink', 'rose pink', 'Rose Pink', 1.00, 'manual'),
    ('rose', 'rose', 'Rose Pink', 0.58, 'fashion'),
    ('rose-pink lipstick', 'rose pink lipstick', 'Rose Pink', 0.90, 'cosmetic'),
    ('soft rose pink', 'soft rose pink', 'Rose Pink', 0.90, 'retail'),
    ('runway rose pink', 'runway rose pink', 'Rose Pink', 0.86, 'designer'),
    ('rose-pink streetwear', 'rose pink streetwear', 'Rose Pink', 0.82, 'streetwear'),
    ('rose aesthetic', 'rose aesthetic', 'Rose Pink', 0.78, 'social_media'),
    ('rose pink colour', 'rose pink colour', 'Rose Pink', 0.88, 'regional'),
    ('tea rose pink', 'tea rose pink', 'Rose Pink', 0.76, 'marketing'),
    ('silken rose', 'silken rose', 'Rose Pink', 0.86, 'luxury'),
    ('vintage rose pink', 'vintage rose pink', 'Rose Pink', 0.80, 'vintage'),
    ('rose pink crepe', 'rose pink crepe', 'Rose Pink', 0.92, 'textile')
), resolved AS (
    SELECT s.term, s.normalized_term, c.color_id,
           s.confidence_weight::REAL, s.source
    FROM seed s
    JOIN public.color_canonical c ON c.canonical_name = s.canonical_name
)
INSERT INTO public.color_lexicon (
    term, normalized_term, color_id, confidence_weight, source
)
SELECT term, normalized_term, color_id, confidence_weight, source
FROM resolved
ON CONFLICT (normalized_term) DO UPDATE SET
    term = EXCLUDED.term,
    color_id = EXCLUDED.color_id,
    confidence_weight = EXCLUDED.confidence_weight,
    source = EXCLUDED.source;

DO $validation$
BEGIN
    IF (
        SELECT count(*)
        FROM public.color_lexicon
        WHERE normalized_term IN (
            SELECT public.normalize_color_term(v.term)
            FROM (VALUES
                ('Black'), ('Charcoal'), ('Gray'), ('Silver'), ('White'),
                ('Ivory'), ('Cream'), ('Beige'), ('Tan'), ('Brown'),
                ('Chocolate'), ('Red'), ('Scarlet'), ('Crimson'), ('Burgundy'),
                ('Coral Red'), ('Orange'), ('Peach'), ('Yellow'), ('Butter Yellow'),
                ('Gold'), ('Green'), ('Olive'), ('Sage'), ('Mint'), ('Emerald'),
                ('Lime'), ('Blue'), ('Navy'), ('Cobalt Blue'), ('Azure'),
                ('Sky Blue'), ('Denim Blue'), ('Purple'), ('Violet'),
                ('Lavender'), ('Pink'), ('Powder Pink'), ('Fuchsia'), ('Rose Pink')
            ) AS v(term)
        )
    ) <> 40 THEN
        RAISE EXCEPTION 'Canonical self-term coverage check failed after lexicon seed.';
    END IF;
END
$validation$;

COMMIT;
